### PR TITLE
add: Bayesian Optimization

### PR DESCRIPTION
**Pull request by mainyaa**
I trying Bayesian Optimization for parameter search :D 
Its fun!

```
pip install
python evolution_bayes.py
```

gekkoJaponicus is awesome!

### CODE REVIEW

**Comment by Gab0** [comment]
Man I'm yet to understand what is this all about.. could you explain? xd
Will accept the pull request to examine hehe

**Comment by mainyaa** [comment]
Short description :D 
 - Bayesian Optimization is MachineLearning Hyperparameter search approach.
 - [Overview](https://github.com/fmfn/BayesianOptimization), [notebook](https://github.com/fmfn/BayesianOptimization/blob/master/examples/visualization.ipynb), [paper](https://arxiv.org/pdf/1012.2599v1.pdf)

1st Evaluate step by step:
- initialize search parameter range(1-30)
```
    bo = BayesianOptimization(gekko_search, {
            "short": (1,30),
        })
```
- `gekko_search` is post gekko `num_boost` times
  - get statics
  - get mean of scores
- bayes_opt search next parameter
- after `num_iter` times bayes_opt returns maximize score and the parameter

2nd Evaluate step by step:
- post `gekko_search` 1st results parameter
- get statics

3rd Evaluate step by step:
- post `Evalute` 1st results parameter with recent dates
- get scores

now, print all results config.js like!

exec hisotry
```zsh
python evolution_bayes.py
/Users/kazuyukimori/miniconda2/envs/py3/lib/python3.6/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The finance module has been deprecated in mpl 2.0 and will be removed in mpl 2.2. Please use the module mpl_finance instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

Starting search PPO parameters
Initialization
--------------------------------------------------------------------------------------------------------------------------------------------
 Step |   Time |      Value |      down |   fibonacci |      high |   interval |      long |       low |     short |    signal |        up |
    1 | 00m16s |   -1.76938 |   -0.0227 |      0.1297 |   55.0206 |    10.4506 |    5.7913 |    8.1789 |   24.4090 |    8.7741 |   -0.0070 |
    2 | 00m14s |   -1.77354 |   -0.0201 |      0.1180 |   46.9976 |    14.1777 |   22.0352 |    6.3572 |   29.7332 |    9.5566 |   -0.0039 |
    3 | 00m14s |    0.68686 |    0.0027 |      0.1174 |   69.7231 |    11.2727 |   28.2915 |   23.7917 |   21.4918 |    5.1232 |   -0.0007 |
    4 | 00m14s |    0.58340 |   -0.0045 |      0.1711 |   50.2051 |     6.8939 |   16.6527 |   25.3064 |   14.2008 |    8.0643 |    0.0172 |
    5 | 00m14s |   -2.53732 |   -0.0038 |      0.1596 |   49.6540 |     5.4822 |    5.5523 |   29.0704 |   27.4485 |    7.6036 |   -0.0025 |
    6 | 00m14s |   -0.61276 |   -0.0246 |      0.1097 |   65.3828 |     7.7918 |   16.2301 |   28.2590 |   20.6371 |    5.0326 |    0.0169 |
    7 | 00m14s |   -2.63038 |   -0.0045 |      0.1505 |   47.3065 |    14.5271 |    5.6247 |   11.4717 |   21.0198 |    9.5425 |   -0.0107 |
    8 | 00m14s |   -0.57472 |   -0.0023 |      0.1926 |   57.9233 |    14.0721 |   19.9118 |   24.4124 |    5.3800 |    7.6151 |   -0.0226 |
    9 | 00m14s |   -1.39739 |    0.0244 |      0.1031 |   46.7753 |     6.6894 |   24.8706 |    3.9297 |   26.9512 |    6.5720 |   -0.0136 |
Bayesian Optimization
--------------------------------------------------------------------------------------------------------------------------------------------
 Step |   Time |      Value |      down |   fibonacci |      high |   interval |      long |       low |     short |    signal |        up |
   10 | 00m28s |   -1.50864 |    0.0007 |      0.1727 |   45.0000 |     3.0000 |   30.0000 |   30.0000 |    9.8436 |    8.3867 |    0.0250 |
   11 | 00m20s |    0.45757 |    0.0250 |      0.2000 |   70.0000 |    15.0000 |   30.0000 |   30.0000 |   30.0000 |   10.0000 |    0.0250 |
   12 | 00m22s |   -3.73078 |    0.0250 |      0.1000 |   70.0000 |     3.0000 |   30.0000 |    3.0000 |    1.0000 |    5.0000 |    0.0250 |
   13 | 00m22s |    1.34156 |    0.0250 |      0.1000 |   70.0000 |     3.0000 |   30.0000 |   30.0000 |   30.0000 |    5.0000 |   -0.0250 |
   14 | 00m15s |   -4.19176 |   -0.0250 |      0.1000 |   70.0000 |     3.0000 |   30.0000 |   21.4372 |   30.0000 |   10.0000 |   -0.0250 |
   15 | 00m16s |    2.39793 |   -0.0043 |      0.1738 |   49.9296 |     7.2529 |   16.9240 |   23.8986 |   14.8834 |    8.1157 |    0.0133 |
   16 | 00m17s |    1.49895 |   -0.0002 |      0.1578 |   49.6135 |     6.9895 |   16.5953 |   23.5206 |   15.2719 |    7.9740 |    0.0144 |
   17 | 00m22s |    2.66458 |   -0.0086 |      0.1928 |   50.1327 |     7.7335 |   17.4302 |   23.5707 |   14.8160 |    8.2991 |    0.0101 |
   18 | 00m17s |    0.69192 |    0.0215 |      0.1867 |   49.8516 |     7.1987 |   17.7204 |   23.7238 |   14.6888 |    8.9841 |    0.0046 |
   19 | 00m19s |    2.92742 |   -0.0250 |      0.1911 |   50.3050 |     7.9460 |   17.0264 |   23.6966 |   14.8663 |    7.7238 |    0.0156 |
   20 | 00m19s |    2.21454 |   -0.0250 |      0.1812 |   50.1066 |     8.3011 |   16.9115 |   23.9197 |   15.1943 |    8.2395 |    0.0089 |
   21 | 00m15s |   -0.35164 |   -0.0250 |      0.1000 |   50.5501 |     7.6078 |   17.5605 |   23.7778 |   15.2494 |    7.6229 |   -0.0250 |
   22 | 00m15s |   -2.22440 |   -0.0027 |      0.1339 |   50.5638 |     9.5883 |   16.9999 |   22.9029 |   14.3870 |    8.9345 |    0.0120 |
   23 | 00m15s |    0.90952 |   -0.0155 |      0.2000 |   49.9866 |     7.8568 |   16.9021 |   23.6336 |   14.7373 |    8.0726 |    0.0250 |
   24 | 00m18s |   -0.23190 |    0.0003 |      0.1355 |   50.1232 |     8.1006 |   17.2066 |   22.6711 |   14.7146 |    8.1895 |   -0.0211 |
   25 | 00m16s |    1.44720 |   -0.0212 |      0.1716 |   51.4082 |     7.9148 |   16.5273 |   25.8905 |   14.2765 |    8.3643 |   -0.0015 |
   26 | 00m33s |    0.40166 |   -0.0245 |      0.1205 |   50.0066 |     7.1663 |   18.7111 |   23.5567 |   13.5504 |    8.5142 |   -0.0220 |
   27 | 00m15s |   -0.12303 |    0.0155 |      0.1998 |   50.8577 |     7.9102 |   16.7028 |   23.8209 |   13.6774 |    6.3931 |    0.0196 |
   28 | 00m15s |    0.83111 |   -0.0177 |      0.1953 |   61.9066 |    13.8625 |   19.0538 |   28.5377 |    7.7773 |    7.6235 |   -0.0003 |
   29 | 00m17s |   -1.00221 |    0.0080 |      0.1338 |   61.4234 |    14.4503 |   19.2947 |   28.7288 |    7.6461 |    7.2014 |    0.0027 |
   30 | 00m17s |    0.79580 |   -0.0181 |      0.1105 |   49.2657 |     8.1466 |   16.8048 |   23.4826 |   15.1960 |    9.3966 |   -0.0186 |
   31 | 00m15s |    0.59078 |   -0.0234 |      0.1788 |   52.2550 |     7.8686 |   16.5978 |   24.9042 |   15.1779 |    8.4346 |   -0.0057 |
   32 | 00m17s |    2.92522 |    0.0068 |      0.1689 |   51.1929 |     6.9915 |   17.3035 |   25.9463 |   13.0537 |    7.8939 |    0.0206 |
   33 | 00m18s |   -0.46583 |    0.0023 |      0.1695 |   51.1897 |     7.1236 |   17.1707 |   25.9087 |   13.2738 |    7.9683 |    0.0173 |
   34 | 00m21s |   -5.08516 |    0.0101 |      0.1186 |   68.3427 |    13.5919 |   18.0189 |   27.7554 |   23.4793 |    6.5404 |    0.0177 |

// --------------------------------------------------
// PPO Settings
// --------------------------------------------------
// 1st Evaluate:
// count: 20.000
// mean: 2.927
// std: 6.885
// min: -11.340
// 25%: -0.860
// 50%: 1.963
// 75%: 6.626
// max: 16.861
// --------------------------------------------------
// 2nd Evaluate:
// count: 20.000
// mean: 3.092
// std: 8.288
// min: -10.674
// 25%: -2.894
// 50%: 2.825
// 75%: 6.213
// max: 18.363
// --------------------------------------------------
// 3rd Evaluate nearest date: 2017-08-04 01:17:00 to 2017-08-07 01:17:00
// Evaluted Score: 12.146015
// --------------------------------------------------
config.PPO = {
  "thresholds": {
    "down": -0.025,
    "up": 0.015649753860619786,
    "low": 23.696624710150076,
    "high": 50.30503212173271,
    "persistence": 1,
    "fibonacci": 0.19108865322619972
  },
  "short": 14.866320102338367,
  "long": 17.026432689286704,
  "signal": 7.723849816918399,
  "interval": 7.945997175113898
}
// --------------------------------------------------
```

**Comment by Gab0** [comment]
Nice, so 'value' in the big table is the profit of the strat running those parameters?

**Comment by mainyaa** [comment]
That's right. It is the "average" of the execution results of Backtest random dates.
I am afraid Loss Cut, so I print  "minimum", "maximum" and other stats xD

**Pull request merged**
